[platformio]
src_dir = app2aeu

[env:esp32dev]
platform = espressif32@6.13.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.filesystem = littlefs

# app2aeu uses the legacy ESP32 Arduino I2S API from Arduino core 2.x.
build_flags =
  -DCORE_DEBUG_LEVEL=0
