#!/usr/bin/env python3
"""
ingest_fpga_synthesis.py — Gowin EDA synthesis report ingestion

Target device : Tang Primer 25K  GW5A-LV25MG121C1/I0
EDA tool      : Gowin EDA (GowinSynthesis + GowinPnR)

Parses Gowin EDA output reports and writes:
  verification/reports/fpga_synthesis.json
  verification/reports/fpga_synthesis_table.md

GW5A-LV25MG121C1/I0 capacity reference
---------------------------------------
  LUT4         20 736
  FF           20 736
  BSRAM (18 kb)    28   (each tile usable as 18k or 2×9k)
  DSP (18×18)      28
  User I/O         84   (MG121 package)

Usage
-----
# Parse Gowin EDA reports after impl:
  python3 verification/scripts/ingest_fpga_synthesis.py \\
      --syn   /path/to/impl/gwsynthesis/hearing_aid_syn.rpt.html \\
      --pnr   /path/to/impl/pnr/hearing_aid.rpt.txt \\
      --power /path/to/impl/pnr/hearing_aid.power.html

# Write blank template (fill numbers manually):
  python3 verification/scripts/ingest_fpga_synthesis.py --template

Report file locations (Gowin EDA project defaults)
---------------------------------------------------
  Synthesis report   : <project>/impl/gwsynthesis/<top>_syn.rpt.html
                       or <project>/impl/gwsynthesis/<top>.log
  PnR report         : <project>/impl/pnr/<top>.rpt.txt
                       or <project>/impl/pnr/<top>.log
  Timing report      : <project>/impl/pnr/<top>_tr_content.html
                       (auto-fallback if --pnr lacks Fmax)
  Power report       : <project>/impl/pnr/<top>.power.html
                       (generated by Gowin Power Analyzer, optional)

JSON fields
-----------
  lut4       LUT4 primitives used.
  ff         Flip-flop / register primitives used.
  bsram18    BSRAM 18k tiles used (each tile = 18 kb).
  dsp        DSP 18×18 blocks used.
  fmax_mhz   Achieved clock frequency in MHz (from PnR timing summary).
  power_mw   Total estimated power in mW (from power report, or null).
  device     Part string, e.g. "GW5A-LV25MG121C1/I0".
  tool       Gowin EDA version string.
  notes      Free-form annotation.
"""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path

REPO_ROOT   = Path(__file__).resolve().parents[2]
REPORTS_DIR = REPO_ROOT / "verification" / "reports"
OUT_JSON    = REPORTS_DIR / "fpga_synthesis.json"
OUT_MD      = REPORTS_DIR / "fpga_synthesis_table.md"

# GW5A-LV25MG121C1/I0 capacity — used in utilisation % column of the table.
_CAPACITY = {
    "lut4":    20_736,
    "ff":      20_736,
    "bsram18":     28,
    "dsp":         28,
}

# ---------------------------------------------------------------------------
# GowinSynthesis report parser
# ---------------------------------------------------------------------------

def _parse_syn(text: str) -> dict[str, int | None]:
    """
    Extract resource counts from a GowinSynthesis report.

    GowinSynthesis writes a section like (field names vary by EDA version):

        Resource Usage
                 LUT : 1234
                  FF : 2345
            BSRAM(9) :    0
           BSRAM(18) :    4
                 DSP :   12
                  IO :   20
              GLOBAL :    4

    or (newer versions):

        LUT4         :  1234
        DFF          :  2345
        BSRAM_18K    :     4
        DSP18        :    12
    """
    return _parse_resources(text)


# ---------------------------------------------------------------------------
# GowinPnR report parser (timing + resource cross-check)
# ---------------------------------------------------------------------------

def _parse_pnr(text: str) -> dict:
    """
    Extract Fmax and (optionally) resource counts from a GowinPnR report.

    GowinPnR timing summary (various formats):

      Format A (common in EDA 1.9.x):
        Clock clk:
          Required: 10.000 ns  (100.000 MHz)
          Actual:    9.503 ns  (105.234 MHz)
          WNS:       0.497 ns

      Format B (single-line):
        clk  Fmax=105.23MHz  WNS=0.497ns

      Format C (table):
        | clk | 100.00 | 105.23 | 0.497 | MET |

      Format D (plain text):
        Max Frequency: 105.234 MHz

    Resource summary in PnR report:
        LUT4:    1234/20736  (5.95%)
        FF:      2345/20736 (11.31%)
        BSRAM18:    4/28    (14.29%)
        DSP:       12/28    (42.86%)
    """
    result: dict = _parse_resources(text)
    result["fmax_mhz"] = _parse_fmax(text)
    return result


# ---------------------------------------------------------------------------
# Gowin power report parser
# ---------------------------------------------------------------------------

def _parse_power(text: str) -> float | None:
    """
    Extract total power (mW) from a Gowin Power Analyzer report.

    Common formats:
      Total Power: 123.45 mW
      Total Power : 0.12345 W
      Total: 123.45 mW
    """
    plain = _to_plain(text)

    # HTML table style: "Total Power (mW)" followed by value cell.
    m = re.search(r"Total\s+Power\s*\(\s*mW\s*\)\s*([0-9]+(?:\.[0-9]+)?)", plain, re.IGNORECASE)
    if m:
        return round(float(m.group(1)), 2)

    # mW directly
    m = re.search(r"Total\s+(?:On-Chip\s+)?Power\s*:?\s*([\d.]+)\s*mW", plain, re.IGNORECASE)
    if m:
        return round(float(m.group(1)), 2)

    # Watts -> mW
    m = re.search(r"Total\s+(?:On-Chip\s+)?Power\s*:?\s*([\d.]+)\s*W\b", plain, re.IGNORECASE)
    if m:
        return round(float(m.group(1)) * 1000.0, 2)

    return None


# ---------------------------------------------------------------------------
# Merge: synthesis takes precedence; PnR fills gaps
# ---------------------------------------------------------------------------

def _merge(syn: dict, pnr: dict) -> dict:
    """
    Synthesis data takes precedence; PnR fills in missing fields.

    If synthesis LUT parsing is obviously bad (e.g. "2" from LUT2 token),
    prefer the PnR value.
    """
    merged: dict = {}
    for key in ("lut4", "ff", "bsram18", "dsp"):
        syn_v = syn.get(key)
        pnr_v = pnr.get(key)
        chosen = syn_v if syn_v is not None else pnr_v
        if key == "lut4" and syn_v is not None and pnr_v is not None:
            # Two known cases:
            # 1) bad synthesis parse (e.g., "2" from LUT2 token),
            # 2) tiny post-PnR accounting delta from synthesis.
            if syn_v < 10 and pnr_v >= 100:
                chosen = pnr_v
            elif abs(pnr_v - syn_v) <= max(16, int(0.01 * pnr_v)):
                chosen = pnr_v
        merged[key] = chosen
    merged["fmax_mhz"] = pnr.get("fmax_mhz")
    return merged


# ---------------------------------------------------------------------------
# Output writers
# ---------------------------------------------------------------------------

def _util_pct(used: int | None, cap: int) -> str:
    if used is None:
        return "—"
    return f"{used:,} / {cap:,}  ({100.0 * used / cap:.1f}%)"


def _write_json(record: dict) -> None:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    with OUT_JSON.open("w", encoding="utf-8") as fh:
        json.dump(record, fh, indent=2)
    print(f"Wrote {OUT_JSON}")


def _write_md(record: dict) -> None:
    def _fmt(v, suffix: str = "") -> str:
        return "—" if v is None else f"{v}{suffix}"

    lut4    = record.get("lut4")
    ff      = record.get("ff")
    bsram18 = record.get("bsram18")
    dsp     = record.get("dsp")

    lines = [
        "# FPGA Synthesis Results",
        "",
        f"> **Tool:** {record.get('tool', '—')}  "
        f"**Device:** {record.get('device', '—')}",
        "",
        "| Resource | Used / Available | Utilisation |",
        "|---|---|---|",
        f"| LUT4 | {_util_pct(lut4,    _CAPACITY['lut4'])} | |",
        f"| Flip-Flop | {_util_pct(ff, _CAPACITY['ff'])} | |",
        f"| BSRAM 18k | {_util_pct(bsram18, _CAPACITY['bsram18'])} | |",
        f"| DSP 18×18 | {_util_pct(dsp,     _CAPACITY['dsp'])} | |",
        f"| **F_max** | **{_fmt(record.get('fmax_mhz'), ' MHz')}** | |",
        f"| Total power | {_fmt(record.get('power_mw'), ' mW')} | |",
        "",
    ]
    if record.get("notes"):
        lines += [f"*{record['notes']}*", ""]

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    with OUT_MD.open("w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"Wrote {OUT_MD}")


# ---------------------------------------------------------------------------
# Template
# ---------------------------------------------------------------------------

def _build_template() -> dict:
    return {
        "tool":     "Gowin EDA",
        "device":   "GW5A-LV25MG121C1/I0",
        "lut4":     None,
        "ff":       None,
        "bsram18":  None,
        "dsp":      None,
        "fmax_mhz": None,
        "power_mw": None,
        "notes":    (
            "Tang Primer 25K — GW5A-LV25MG121C1/I0.  "
            "Fill from impl/gwsynthesis/*.rpt and impl/gwpnr/*.rpt."
        ),
    }


# ---------------------------------------------------------------------------
# Generic helpers / parsers
# ---------------------------------------------------------------------------

def _to_plain(text: str) -> str:
    """Convert mixed HTML/text report content into plain text for regex parsing."""
    plain = html.unescape(text)
    plain = re.sub(r"(?i)<br\s*/?>", "\n", plain)
    plain = re.sub(r"(?i)</(tr|p|h[1-6]|table|div|li|td|th)>", "\n", plain)
    plain = re.sub(r"<[^>]+>", " ", plain)
    plain = plain.replace("&nbsp;", " ")
    plain = plain.replace("\r", "\n")
    plain = re.sub(r"[ \t\f\v]+", " ", plain)
    plain = re.sub(r"\n\s+", "\n", plain)
    plain = re.sub(r"\n{2,}", "\n", plain)
    return plain


def _first_int(patterns: list[str], text: str) -> int | None:
    for pat in patterns:
        m = re.search(pat, text, re.IGNORECASE | re.DOTALL)
        if m:
            return int(m.group(1))
    return None


def _parse_resources(text: str) -> dict[str, int | None]:
    """
    Parse LUT/FF/BSRAM/DSP from Gowin reports (HTML or text).

    Handles both synthesis and PnR report styles.
    """
    plain = _to_plain(text)
    out: dict[str, int | None] = {"lut4": None, "ff": None, "bsram18": None, "dsp": None}

    # LUT: prefer total "Logic X(... LUT ...)" or "Logic X/Y" rows.
    out["lut4"] = _first_int([
        r"\bLogic\b[^\n]*\|\s*(\d+)\s*/\s*\d+",
        r"\bLogic\b\s*(?:\n\s*)?(\d+)\s*\(\s*\d+\s+LUT\b",
        r"\bLogic\b\s*(?:\n\s*)?(\d+)\s*/\s*\d+",
        r"\bLUT4\b\s*:?\s*(\d+)\b",
        r"\bLUT\b\s*:?\s*(\d+)\s*/\s*\d+",
        r"\bLUT\b\s*:?\s*(\d+)\b",
    ], plain)

    # FF: prefer total register row.
    out["ff"] = _first_int([
        r"\bRegister\b[^\n]*\|\s*(\d+)\s*/\s*\d+",
        r"\bRegister\b\s*(?:\n\s*)?(\d+)\s*/\s*\d+",
        r"\bFF\b\s*:?\s*(\d+)\s*/\s*\d+",
        r"\bDFF\b\s*:?\s*(\d+)\s*/\s*\d+",
        r"\bRegisters?\b\s*:?\s*(\d+)\b",
    ], plain)
    if out["ff"] is None:
        logic_ff = _first_int([r"\bLogic Register as FF\b[^\n]*?(\d+)\s*/\s*\d+"], plain)
        io_ff = _first_int([r"\bI/O Register as FF\b[^\n]*?(\d+)\s*/\s*\d+"], plain)
        if logic_ff is not None:
            out["ff"] = logic_ff + (io_ff or 0)

    # BSRAM: prefer table usage row, then explicit BSRAM(18).
    out["bsram18"] = _first_int([
        r"\bBSRAM\b[^\n]*\|\s*(\d+)\s*/\s*\d+",
        r"\bBSRAM\b\s*(?:\n\s*)?(\d+)\s*/\s*\d+",
        r"\bBSRAM[_(]?18[Kk)]?\b\s*:?\s*(\d+)\b",
        r"\bBSRAM18\b\s*:?\s*(\d+)\b",
        r"\bBSRAMs?\b\s*:?\s*(\d+)\b",
    ], plain)

    # DSP: prefer table usage row.
    out["dsp"] = _first_int([
        r"\bDSP\b[^\n]*\|\s*(\d+)\s*/\s*\d+",
        r"\bDSP\b\s*(?:\n\s*)?(\d+)\s*/\s*\d+",
        r"\bDSP(?:18K?)?\b\s*:?\s*(\d+)\b",
        r"\bMultiplier\b\s*:?\s*(\d+)\b",
    ], plain)

    return out


def _parse_fmax(text: str) -> float | None:
    """Extract Fmax (MHz) from Gowin timing reports in text or HTML form."""
    plain = _to_plain(text)

    # HTML table style:
    # Max Frequency Summary -> clk -> Constraint(MHz) -> Actual Fmax(MHz)
    m = re.search(
        r"\bMax Frequency Summary\b.*?\bclk\b.*?(\d+(?:\.\d+)?)\s*\(\s*MHz\s*\).*?"
        r"(\d+(?:\.\d+)?)\s*\(\s*MHz\s*\)",
        plain,
        re.IGNORECASE | re.DOTALL,
    )
    if m:
        return round(float(m.group(2)), 2)

    # Alternate table/summary style with explicit "Actual Fmax" label.
    m = re.search(r"\bActual\s*Fmax\b[^0-9]*?(\d+(?:\.\d+)?)\s*\(\s*MHz\s*\)", plain, re.IGNORECASE)
    if m:
        return round(float(m.group(1)), 2)

    # "Actual: 9.503 ns (105.234 MHz)"
    m = re.search(r"Actual\s*:\s*[\d.]+\s*ns\s*\((\d+\.?\d*)\s*MHz\)", plain, re.IGNORECASE)
    if m:
        return round(float(m.group(1)), 2)

    # "Fmax=105.23MHz"
    m = re.search(r"Fmax\s*=\s*([\d.]+)\s*MHz", plain, re.IGNORECASE)
    if m:
        return round(float(m.group(1)), 2)

    # "Max Frequency: 105.234 MHz"
    m = re.search(r"Max(?:imum)?\s+Freq(?:uency)?\s*:?\s*([\d.]+)\s*MHz", plain, re.IGNORECASE)
    if m:
        return round(float(m.group(1)), 2)

    # Fallback from Required/WNS.
    req = re.search(r"Required\s*:\s*([\d.]+)\s*ns", plain, re.IGNORECASE)
    wns = re.search(r"WNS\s*:\s*([\d.]+)\s*ns", plain, re.IGNORECASE)
    if req and wns:
        period = float(req.group(1)) - float(wns.group(1))
        if period > 0:
            return round(1000.0 / period, 2)

    return None


def _parse_device(text: str) -> str | None:
    """Extract part number string from synthesis/PnR report body."""
    # Match literal "<Part Number>:" before any HTML-like normalization.
    m = re.search(r"<Part Number>:\s*([A-Za-z0-9_./-]+)", text, re.IGNORECASE)
    if m:
        return m.group(1)

    plain = _to_plain(text)
    m = re.search(r"\bPart Number\b[^A-Za-z0-9]+([A-Za-z0-9_./-]+)", plain, re.IGNORECASE)
    if m:
        return m.group(1)
    return None


def _infer_top_name(report_path: Path) -> str:
    name = report_path.name
    for suffix in (".rpt.txt", ".rpt.html", ".rpt", ".log", ".txt", ".html"):
        if name.endswith(suffix):
            return name[: -len(suffix)]
    return report_path.stem


def _related_timing_reports(pnr_path: Path) -> list[Path]:
    top = _infer_top_name(pnr_path)
    return [
        pnr_path.parent / f"{top}_tr_content.html",
        pnr_path.parent / f"{top}.tr.html",
    ]


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> None:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--syn", metavar="FILE",
        help="GowinSynthesis report (.html/.txt/.log)",
    )
    p.add_argument(
        "--pnr", metavar="FILE",
        help="GowinPnR report (.txt/.html/.log); Fmax auto-fallback uses sibling timing HTML",
    )
    p.add_argument(
        "--power", metavar="FILE",
        help="Gowin Power Analyzer report (optional; .html/.txt)",
    )
    p.add_argument(
        "--device", metavar="PART",
        default=None,
        help="Part string override (default: auto-detect from report)",
    )
    p.add_argument(
        "--tool", metavar="STR",
        default="Gowin EDA",
        help='Tool + version string (default: "Gowin EDA")',
    )
    p.add_argument(
        "--notes", metavar="STR", default="",
        help="Free-form annotation appended to the Markdown table",
    )
    p.add_argument(
        "--template", action="store_true",
        help="Write a blank template without parsing any file",
    )
    args = p.parse_args(argv)

    if args.template:
        record = _build_template()
        _write_json(record)
        _write_md(record)
        return

    record = _build_template()
    record["tool"] = args.tool
    if args.device:
        record["device"] = args.device
    if args.notes:
        record["notes"] = args.notes

    syn_data: dict = {}
    pnr_data: dict = {}
    detected_device: str | None = None

    if args.syn:
        text = Path(args.syn).read_text(encoding="utf-8", errors="replace")
        syn_data = _parse_syn(text)
        if detected_device is None:
            detected_device = _parse_device(text)
        missing = [k for k, v in syn_data.items() if v is None]
        if missing:
            print(f"NOTE: could not parse from synthesis report: {missing}",
                  file=sys.stderr)

    if args.pnr:
        pnr_path = Path(args.pnr)
        text = pnr_path.read_text(encoding="utf-8", errors="replace")
        pnr_data = _parse_pnr(text)
        if detected_device is None:
            detected_device = _parse_device(text)
        if pnr_data.get("fmax_mhz") is None:
            for candidate in _related_timing_reports(pnr_path):
                if not candidate.exists():
                    continue
                extra = candidate.read_text(encoding="utf-8", errors="replace")
                extra_data = _parse_pnr(extra)
                if detected_device is None:
                    detected_device = _parse_device(extra)
                if extra_data.get("fmax_mhz") is not None:
                    pnr_data["fmax_mhz"] = extra_data["fmax_mhz"]
                    print(f"NOTE: Fmax parsed from related timing report: {candidate}",
                          file=sys.stderr)
                    break
        if pnr_data.get("fmax_mhz") is None:
            print("WARNING: Fmax not found in PnR report — check report format.",
                  file=sys.stderr)

    merged = _merge(syn_data, pnr_data)
    record.update(merged)

    if not args.device and detected_device:
        record["device"] = detected_device

    if args.power:
        text = Path(args.power).read_text(encoding="utf-8", errors="replace")
        mw = _parse_power(text)
        if mw is not None:
            record["power_mw"] = mw
        else:
            print("WARNING: total power not found in power report.", file=sys.stderr)

    if not args.notes and detected_device and detected_device != _build_template()["device"]:
        record["notes"] = (
            f"Tool-reported device: {detected_device}. "
            "Board docs may label this as GW5A-LV25MG121C1/I0."
        )

    _write_json(record)
    _write_md(record)


if __name__ == "__main__":
    main()
